apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ${{release}}

on:
  push:
    branches:
      - '**'
jobs:
  build:
    steps:
      - name: compile
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Building ${appname} with ${build.type} ${build.args}"
  analyze:
    steps:
      - name: scan
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Analyzing"
  deploy-qa:
    needs: build
    environment: qa
    steps:
      - name: deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Deploying ${appname} with ${deploy.target} ${deploy.args} to qa"
  deploy-production:
    needs: deploy-qa
    environment: production
    steps:
      - name: deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Deploying ${appname} ${deploy.target} ${deploy.args} to production"
