apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Generate application release from template

on:
  push:
    branches:
      - '**'
permissions:
  scm-token-own: read
  scm-token-org: read
jobs:
  build:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
      - name: Git global credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
        with:
          token: ${{ cloudbees.scm.token }}
      - name: Clone app code
        uses: docker://alpine/git:latest
        run: |
          export GITHUB_TOKEN=${{ cloudbees.scm.token }}
          git clone https://github.com/cb-demos/VacationRentals.git
      - name: Render release pipeline
        uses: docker://groovy
        run: |
          groovy render.groovy template.yaml VacationRentals/values.yaml >> release.yaml
      - name: Push release workflow to application repository
        uses: docker://alpine/git:latest
        shell: sh
        run: |
          cd VacationRentals
          mkdir -p .cloudbees/workflows
          cp ../release.yaml .cloudbees/workflows/ReleaseV1.yaml
          git commit . -m "Rendered ReleaseV1"
          git push
